name: Lobby-1.8
version: 0.2.0-SNAPSHOT
main: de.icevizion.lobby.LobbyPlugin

author: [theEvilReaper, JumpingPxl]

depend: [Aves-1.8, CloudSpigot, FriendSystem, PartySystem, SpectatorSystem]

commands:
  location: