name: Lobby-1.8
version: 1.1.0
main: de.icevizion.lobby.LobbyPlugin

author: [theEvilReaper, JumpingPxl]

depend: [Aves-1.8, CloudSpigot, FriendSystem, PartySystem, SpectatorSystem]

commands:
  location: